/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EnhancedItems;

public class AppTest {
    /*@Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
    }*/
}
